/*
Copyright The K6s Authors.

*/

// Code generated by informer-gen. DO NOT EDIT.

package blueprintcontroller

import (
	"github.com/farmer-hutao/k6s/pkg/controller"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V1alpha1 provides access to shared informers for resources in V1alpha1.
	V1alpha1() controller.Interface
}

type group struct {
	factory          controller.SharedInformerFactory
	namespace        string
	tweakListOptions controller.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f controller.SharedInformerFactory, namespace string, tweakListOptions controller.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// V1alpha1 returns a new v1alpha1.Interface.
func (g *group) V1alpha1() controller.Interface {
	return controller.New(g.factory, g.namespace, g.tweakListOptions)
}
