/*
Copyright The K6s Authors.

*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BlueprintListerExpansion allows custom methods to be added to
// BlueprintLister.
type BlueprintListerExpansion interface{}

// BlueprintNamespaceListerExpansion allows custom methods to be added to
// BlueprintNamespaceLister.
type BlueprintNamespaceListerExpansion interface{}
