/*
Copyright The K6s Authors.

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/farmer-hutao/paas-operator/pkg/controller/client/clientset/versioned/typed/blueprintcontroller/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeBlueprintcontrollerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeBlueprintcontrollerV1alpha1) Databases(namespace string) v1alpha1.DatabaseInterface {
	return &FakeDatabases{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBlueprintcontrollerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
