/*
Copyright The K6s Authors.

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"github.com/farmer-hutao/k6s/pkg/controller"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/testing"
)

type FakeBlueprintcontrollerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeBlueprintcontrollerV1alpha1) Databases(namespace string) controller.DatabaseInterface {
	return &controller.FakeDatabases{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBlueprintcontrollerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
