/*
Copyright The K6s Authors.

*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/farmer-hutao/k6s/pkg/controller"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Databases returns a DatabaseInformer.
	Databases() controller.DatabaseInformer
}

type version struct {
	factory          controller.SharedInformerFactory
	namespace        string
	tweakListOptions controller.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f controller.SharedInformerFactory, namespace string, tweakListOptions controller.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Databases returns a DatabaseInformer.
func (v *version) Databases() controller.DatabaseInformer {
	return &controller.databaseInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
