/*
Copyright The K6s Authors.

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/farmer-hutao/k6s/pkg/client/clientset/versioned/typed/k6s/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeK6sV1alpha1 struct {
	*testing.Fake
}

func (c *FakeK6sV1alpha1) Blueprints(namespace string) v1alpha1.BlueprintInterface {
	return &FakeBlueprints{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeK6sV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
