// +build !ignore_autogenerated

/*
Copyright The K6s Authors.

*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/farmer-hutao/k6s/pkg/controller"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *controller.AppField) DeepCopyInto(out *controller.AppField) {
	*out = *in
	out.Script = in.Script
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppField.
func (in *controller.AppField) DeepCopy() *controller.AppField {
	if in == nil {
		return nil
	}
	out := new(controller.AppField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *controller.Database) DeepCopyInto(out *controller.Database) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *controller.Database) DeepCopy() *controller.Database {
	if in == nil {
		return nil
	}
	out := new(controller.Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *controller.Database) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *controller.DatabaseList) DeepCopyInto(out *controller.DatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]controller.Database, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseList.
func (in *controller.DatabaseList) DeepCopy() *controller.DatabaseList {
	if in == nil {
		return nil
	}
	out := new(controller.DatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *controller.DatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *controller.DatabaseSpec) DeepCopyInto(out *controller.DatabaseSpec) {
	*out = *in
	out.Host = in.Host
	out.App = in.App
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *controller.DatabaseSpec) DeepCopy() *controller.DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(controller.DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *controller.DatabaseStatus) DeepCopyInto(out *controller.DatabaseStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStatus.
func (in *controller.DatabaseStatus) DeepCopy() *controller.DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(controller.DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *controller.HostField) DeepCopyInto(out *controller.HostField) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostField.
func (in *controller.HostField) DeepCopy() *controller.HostField {
	if in == nil {
		return nil
	}
	out := new(controller.HostField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *controller.ScriptField) DeepCopyInto(out *controller.ScriptField) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptField.
func (in *controller.ScriptField) DeepCopy() *controller.ScriptField {
	if in == nil {
		return nil
	}
	out := new(controller.ScriptField)
	in.DeepCopyInto(out)
	return out
}
