apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: dbs.blueprintcontroller.k8s.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: blueprintcontroller.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: databases
    singular: database
    kind: Database
    shortNames:
      - db
  subresources:
    status: {}